### ISSUE TITLE
We are learning bigger_than as part of the semantics of colors

### ISSUE THREAD

**Issue by gabbard** [isi-vista/adam#715] opened 2020-03-25 14:05 UTC
This is not the relation, but rather the property which indicates an object is bigger than the learner. 

The first thing to check here is whether our color learning curriculum for Phase 1 happens to only include objects larger than the learner.  If so, just adding some small objects may be enough to fix it.

**Comment by denizbeser** [comment] 2020-03-25 15:35
How can replicate this bug? I checked color curriculum and it has examples with both smallerThan and biggerThan properties

**Comment by gabbard** [comment] 2020-03-25 15:38
@denizbeser : Use `run_m9.py` on `m9.debug.py`.  In the code for `log_experiments`, switch the debug curriculum to the color curriculum.  It will log dot plots of the hypotheses learned - take a look at the learned hypotheses to replicate the proble.

**Comment by denizbeser** [comment] 2020-03-25 19:59
@gabbard With object-subset, there are hypotheses with smallerThan too, so it's normal:
[a_dark brown_cookie.pdf](https://github.com/isi-vista/adam/files/4383197/a_dark.brown_cookie.pdf)

Attribute learner is fine too:
[a_green_ball.pdf](https://github.com/isi-vista/adam/files/4383205/a_green_ball.pdf)

Pursuit is fine too:
[a_white_cup.pdf](https://github.com/isi-vista/adam/files/4383225/a_white_cup.pdf)

**Comment by gabbard** [comment] 2020-03-25 20:09
@denizbeser : I don't understand, can you clarify?

**Comment by denizbeser** [comment] 2020-03-25 20:15
@gabbard It's not a bug, but just a consequence of the curriculum. The learner is learning what it's given. E.g for black, we have _car_ and _chair_, both of which are bigger so we get biggerThan in the graph:
[a_black_slot1.pdf](https://github.com/isi-vista/adam/files/4383313/a_black_slot1.pdf)

For white, though, we have _cup_ (small) so we don't get it
[a_white_slot1.pdf](https://github.com/isi-vista/adam/files/4383314/a_white_slot1.pdf)

Should I increase the number of examples in the curriculum?

**Comment by LichMaster98** [comment] 2020-03-25 20:17
@denizbeser What if we switched to using `all_possible` that'll make the curriculum identical to `each_object_by_itself` except the color will be in the English generated but we'll have every possible combination of color and size in our curriculum.

**Comment by denizbeser** [comment] 2020-03-25 20:19
@LichMaster98 Yep, that would work

**Comment by gabbard** [comment] 2020-03-25 20:21
@denizbeser : do that as long as it doesn't blow up the size of the curriculum enough to make things very slow.

**Comment by LichMaster98** [comment] 2020-03-25 20:23
@denizbeser @gabbard It should be 154 examples according to the `each object by itself` curriculum

**Comment by gabbard** [comment] 2020-03-25 20:36
@LichMaster98 @denizbeser : that's acceptable

**Comment by denizbeser** [comment] 2020-03-25 20:37
Sampling 80 was sufficient

**Closed** 2020-03-25 21:10 UTC
Labels: bug
